apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:oCJe1ib04NY=,iv:QZ8gxUmk5IBVzWehNl16zGibjo/pBabdVDnl5vLFq+Y=,tag:epApcklFA2jBUKbtaVT3OQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:aX5hUamkjCNgo67O,iv:KcOeeZ0aEOFDoouSXIESrs2fV2I3lST3j1+TmNkynv8=,tag:5qw6phJwZUrgP/Gf6r+0gQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1hz2c3flk90hcc5lml30u2ek8t85cg2kprg9audugkp2k55wknsdqvtn55s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NXJteks3MDM2ZndneDkr
            Y1ZnSVE3V0ZsUXc3Q1k3NDFhWUZQRDJ3UkRJCkdIY3lWUGxWZnliUG5WTkxYOGZR
            YU93NWZiZlVuMnVEZUJ0dVRtcUhJNncKLS0tIGNHcENBcW43OTVuWXZvUnBrczU2
            MXFiTTh0bUw0U1AwYWtNSnhocFFEZkkKQvg02JgLunTmHYXk0pKJRHnB08zdAXIR
            ILrHGMTFNimX0ndmqyZMGih5RAJESP6PgelwH7K4WYZ3pdvRo7jF1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T04:12:01Z"
    mac: ENC[AES256_GCM,data:oZ/Jd+zMzqqAPb5ZuFj8x7985mq9WUt1LnOFFfjqx1L2ilXrEah+jSMLJTPD914GluCO/pyAHnBm+BWGSf/vATV9k6INZPSPSFpP3SUY0pmh7OkkDrUhSQUQp3uKGwVL4XZ/HODLPuQvayhEHKKd3iKQRrIpDM2ryo4nVYYefDg=,iv:QGA2vFAjdcgjmUURwkexxaLDY6H4W0hCNBuB/nyTooU=,tag:LTCnkC68nhvrwv7u1bV54A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
