apiVersion: v1
data:
    password: ENC[AES256_GCM,data:iuNfuQ==,iv:v5x5cMY8hcqQUuGkI9acFsV6Q+sU1ySMBDcZUS1CWP8=,tag:aL9vlLh65qhT3fM0o8o+WQ==,type:str]
    user: ENC[AES256_GCM,data:aoi1qb7rcyA=,iv:Q03p75F5MFk9eML0NLGirhVOD5HR9ezBqZdzoxtkBug=,tag:6y8iE0sxPXX6i+yCXSIiBA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1npxtgvadz8p3pgu5yuevjg34kkmvflg6pg8ck0cyxllxnwnkl3fssjf6ta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK29yamtISXhWV2pHTUdD
            eXp6THBFcWtaNGhEWjJSeUdqbTFrUUN1ald3CklVbHIvb1U2UWc3a2x5MUJkSFQz
            RWQvdkhBZEJxUnlDeGVpVFRKSUlPeTAKLS0tIENmZDNsZHlyV3ZWV2lYTGlrdjZW
            Y0JUYkFLanM2K0o5eXBGZWg4NVBHcmcKdo7I0mg2zhlvBCjP8FRlmS+xGpU86Yeb
            cfl+hAI6E5pQb9SmP7agkOfor3PjlmRRGgWHRLX6yuIsDPFkM1lXyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T23:57:33Z"
    mac: ENC[AES256_GCM,data:kS7S610OnOQGZ/2DwJNlCxi/byYcM6HdDoExmrFre8o2qj/fOt0qOXhWrP9Xnun+SOn8y51kqGBjPIx0iOElCkqaoyXu7W8yCqBPQpAtvWV3mBCNczizrZq9RlaYfZOfFoqsWHmf44GP26mviszbFmGdomHPFNZjp+Zup+Gw3g8=,iv:KMGTciU2CWHClrU3JXriMIZE2Q8Zy5zr1Clfe1uOYV4=,tag:2FYZ2OxIoymvrxXdVu7KAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
