apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  # dependsOn:
  #   - name: infra-configs
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/staging
  prune: true
    # in the apps.yaml Kustomization file, add under spec:
# (same level as prune: true)
  decryption:
    provider: sops
    secretRef:
      name: sops-age
